#!/bin/bash

# Installation script untuk Photo Gallery dengan Supabase

echo "📦 Installing dependencies..."
npm install

echo ""
echo "✅ Dependencies installed!"
echo ""
echo "📋 Setup Instructions:"
echo "1. Buat database di Supabase dengan struktur berikut:"
echo ""
echo "   ===== Table: categories ====="
echo "   - id (bigint, primary key)"
echo "   - name (text, not null)"
echo "   - icon (text, nullable)"
echo "   - created_at (timestamp with timezone)"
echo ""
echo "   ===== Table: photos ====="
echo "   - id (bigint, primary key)"
echo "   - title (text, not null)"
echo "   - description (text, nullable)"
echo "   - drive_id (text, not null)"
echo "   - image_url (text, not null)"
echo "   - category_id (bigint, foreign key to categories.id)"
echo "   - created_at (timestamp with timezone)"
echo ""
echo "2. Copy file .env.example ke .env"
echo "3. Isi .env dengan kredensial Supabase Anda:"
echo "   - SUPABASE_URL"
echo "   - SUPABASE_KEY (anon key untuk frontend)"
echo "   - SUPABASE_SERVICE_ROLE_KEY (untuk backend)"
echo "4. Setup admin credentials dan JWT secret di .env"
echo ""
echo "📝 Contoh .env:"
echo "   SUPABASE_URL=https://xxxxx.supabase.co"
echo "   SUPABASE_KEY=eyJhbGciOiJIUzI1NiIs..."
echo "   SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIs..."
echo "   JWT_SECRET=your_super_secret_jwt_key"
echo "   ADMIN_USERNAME=admin"
echo "   ADMIN_PASSWORD=admin123"
echo "   PORT=5000"
echo ""
echo "🚀 Jalankan server dengan: npm start atau npm run dev"
